{{- if .Values.ciliumNetworkPolicy.enabled -}}
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  labels:
    {{- include "sloth.labels" . | nindent 4 }}
  name: {{ include "sloth.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      {{- include "sloth.selectorLabels" . | nindent 6 }}
  egress:
    - toEntities:
        - kube-apiserver
        ## Needed by the init container to be able ot download sloth plugins.
        - world
    # Allow all DNS queries
    - toEndpoints:
      - matchLabels:
          "k8s:io.kubernetes.pod.namespace": kube-system
          "k8s:k8s-app": coredns
      - matchLabels:
          "k8s:io.kubernetes.pod.namespace": kube-system
          "k8s:k8s-app": k8s-dns-node-cache
      toPorts:
        - ports:
           - port: "1053"
             protocol: ANY
           - port: "53"
             protocol: ANY
          rules:
            dns:
              - matchPattern: "*"
  ingress:
    - fromEntities:
      - cluster
      toPorts:
      - ports:
        - port: "8081"
          protocol: "TCP"
        rules:
          http:
          - method: "GET"
            path: "/metrics"
{{- end -}}
