labels: {}

image:
  registry: gsoci.azurecr.io
  repository: giantswarm/sloth
  tag: v0.13.0

ciliumNetworkPolicy:
  enabled: true

# -- Container resources: requests and limits for CPU, Memory
resources:
  limits:
    cpu: 50m
    memory: 150Mi
  requests:
    cpu: 5m
    memory: 75Mi

imagePullSecrets: []
#  - name: secret1
#  - name: secret2

sloth:
  resyncInterval: ""    # The controller resync interval duration (e.g 15m).
  workers: 0            # The number of concurrent controller workers (e.g 5).
  labelSelector: ""     # Sloth will handle only the ones that match the selector.
  namespace: ""         # The namespace where sloth will the CRs to process.
  extraLabels: {}       # Labels that will be added to all the generated SLO Rules.
  defaultSloPeriod: ""  # The slo period used by sloth (e.g. 30d).
  debug:
    enabled: false
  # Could be: default or json
  logger: default

commonPlugins:
  enabled: true
  image:
    registry: gsoci.azurecr.io
    repository: giantswarm/git-sync
    tag: v4.5.0
  gitRepo:
    url: https://github.com/slok/sloth-common-sli-plugins
    ref: main
    resources:
      limits:
        cpu: 50m
        memory: 100Mi
      requests:
        cpu: 5m
        memory: 50Mi

metrics:
  enabled: true
  #scrapeInterval: 30s
  prometheusLabels: {}

customSloConfig:
  enabled: false
  path: /windows
  data: {}
#    apiVersion: sloth.slok.dev/v1
#    kind: AlertWindows
#    spec:
#    ... See https://sloth.dev/usage/slo-period-windows/

# add deployment pod tolerations
# tolerations:
#   - key: kubernetes.azure.com/scalesetpriority
#     operator: Equal
#     value: spot
#     effect: NoSchedule

securityContext:
  pod:
    runAsNonRoot: true
    runAsUser: 65534
    seccompProfile:
      type: RuntimeDefault
  container:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop:
        - ALL
